export const STORAGE_KEY = {
  USERS: "USERS",
  PROFILE_ID: "PROFILE_ID",
  ROLE: "ROLE",
  PROFILE_DETAILS: "PROFILE_DETAILS",
  SELECTED_STUDENT_DETAILS: "SELECTED_STUDENT_DETAILS",
  APPOINTMENTS: "APPOINTMENTS",
  MESSAGES: "MESSAGES",
  TOKEN: "TOKEN",
};
